services:
  - type: web
    name: bestCoder1877
    env: python
    runtime:
      version: 3.10
    region: oregon
    autoDeploy: true
    envVars:
      - key: FLASK_APP
        value: app.py
      - key: FLASK_RUN_HOST
        value: 0.0.0.0
      - key: FLASK_RUN_PORT
        value: $PORT
    startCommand: flask run app.py
    buildCommand: pip install -r requirements.txt
    plan: free